name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget cmake make g++ libeigen3-dev libceres-dev

      - name: Build and install GLog from source
        run: |
          # Download and build GLog
          wget https://github.com/google/glog/archive/refs/tags/v0.6.0.tar.gz
          tar -xzf v0.6.0.tar.gz
          cd glog-0.6.0
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
          make -j$(nproc)
          sudo make install
          cd ../../
          rm -rf glog-0.6.0 v0.6.0.tar.gz

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
