name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget cmake make g++ libeigen3-dev libceres-dev libunwind-dev
          sudo apt-get install -y libgoogle-glog-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
